name: aws-glue-s3-plugin
description: AWS Glue S3 Plugin
display-name: aws-glue-s3-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - Terraform
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - env
inputs:
  - label: Criar buckets padrão(data-sor, data-sot, data-spec, data-script e data-athena-output) ou criar um bucket individual?
    type: text
    items:
      - Padrão
      - Individual
    name: creation_decision

  - label: digite o nome do bucket
    type: text
    name: bucket_name
    condition:
      variable: creation_decision
      operator: "=="
      value: Individual

hooks:
  - type: edit
    trigger: after-render
    path: bucket.tf
    condition:
      variable: creation_decision
      operator: "=="
      value: Individual
    changes:
      - insert:
          line: -1
          snippet: snippets/snippet-bucket.tf
          when:
            not-exists: snippets/snippet-bucket.tf
